version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '21:00'
    open-pull-requests-limit: 10
    reviewers:
      - DIYgod
    labels:
      - dependencies
    ignore:

    # ESM only
      - dependency-name: got
        versions:
          - '>=12.0.0'
      - dependency-name: ip-regex
        versions:
          - '>=5.0.0'
      - dependency-name: remark
        versions:
          - '>=14.0.0'
      - dependency-name: remark-frontmatter
        versions:
          - '>=4.0.0'
      - dependency-name: remark-preset-prettier
        versions:
          - '>=1.0.0'
      - dependency-name: string-width
        versions:
          - '>=5.0.0'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
      time: '21:00'
    open-pull-requests-limit: 10
    reviewers:
      - DIYgod
    labels:
      - dependencies
