version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '21:00'
    open-pull-requests-limit: 10
    labels:
      - dependencies
    ignore:
      - dependency-name: jsrsasign
        versions: ['>=11.0.0'] # no longer includes KJUR.crypto.Cipher for RSA
      - dependency-name: unified
        versions: ['>=10.0.0']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
      time: '21:00'
    open-pull-requests-limit: 10
    labels:
      - dependencies
