# This is a basic workflow to help you get started with Actions

name: deploy docs staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [deploy-staging]
    pull_request:
        branches: [deploy-staging]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x

            # Runs a single command using the runners shell
            - name: build
              run: |
                  npm install
                  npm run docs:build

            # Runs a set of commands using the runners shell
            - name: deploy to aliyun oss
              uses: manyuanrong/setup-ossutil@master
              with:
                  endpoint: oss-cn-hangzhou.aliyuncs.com
                  access-key-id: ${{ secrets.ACCESS_KEY_ID }}
                  access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}

            - name: Deply To OSS
              run: ossutil cp docs/.vuepress/dist oss://yanbot-rsshub-docs/ -rf
