name: 'Close stale issues and PRs'

on:
    schedule:
        - cron: '31 23 * * *'

permissions:
    issues: write
    pull-requests: write

jobs:
    stale:
        runs-on: ubuntu-slim
        steps:
            - uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
              with:
                  # Don't stale issues
                  days-before-issue-stale: -1
                  days-before-pr-stale: 23
                  days-before-close: 7
                  stale-pr-message: >
                      This PR is stale because it has been opened for more than 3 weeks with no activity. Comment or this will be closed in 7 days.
                  close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
                  close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
                  exempt-issue-labels: 'wait for upstream'
                  exempt-pr-labels: 'wait for upstream'
                  any-of-issue-labels: 'more data required'
    lock:
        runs-on: ubuntu-slim
        steps:
            - uses: dessant/lock-threads@7266a7ce5c1df01b1c6db85bf8cd86c737dadbe7 # v6.0.0
              with:
                  github-token: ${{ github.token }}
                  process-only: 'prs'
                  pr-inactive-days: '30'
                  pr-comment: >
                      This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
