name: Yarn Lock Changes
on:
  pull_request:
    paths:
      - '.github/workflows/yarn-lock-changes.yml'
      - 'yarn.lock'

jobs:
  yarn_lock_changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Permission overwrite is required for Dependabot PRs, see https://github.com/marketplace/actions/yarn-lock-changes#-common-issues.
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Yarn Lock Changes
        uses: Simek/yarn-lock-changes@v0.11.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
